version: '3.8'
services:
  mariadb10:
    container_name: mariadb10
    image: mariadb:10.7.8-focal
    restart: always
    volumes:
      - /home/administrador/docker/volumes/mariadb10/data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin1342*
      MYSQL_DATABASE: db_posts
      MYSQL_USER: u_post
      MYSQL_PASSWORD: posts1342
    ports:
      - 3306:3306
    
  crud-jaxrs:
    build: 
      context: .
      dockerfile: Dockerfile
    image: roonmorton/crud-jaxrs:v1.0.7
    ports:
      - "8083:8080"
    depends_on:
      - mariadb10